default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  port: 5432

development:
  <<: *default
  host: localhost
  database: splitwise_development
  username: sw_user
  password: ENV['DEV_DB_PASSWORD']

test:
  <<: *default
  host: localhost
  database: splitwise_test
  username: sw_user
  password: ENV['DEV_DB_PASSWORD']

production:
  <<: *default
  host: <%= ENV["PROD_DB_HOST"] %>
  database: <%= ENV["PROD_DB_NAME"] %>
  username: <%= ENV["PROD_DB_USERNAME"] %>
  password: <%= ENV["PROD_DB_PASSWORD"] %>
